sudo: false

language: node_js

node_js:
  - '4.0'
  - '5.0'
  - '6.0'

before_install:
  - npm update -g npm

after_script:
  - npm run coveralls

after_failure:
  - tar -cjf "svg-sprite_travis_${TRAVIS_BUILD_NUMBER}.tar.bz2" tmp && curl --ftp-create-dirs -T "svg-sprite_travis_${TRAVIS_BUILD_NUMBER}.tar.bz2" -u $FTP_USER:$FTP_PASSWORD "ftp://jkphl.is/${TRAVIS_REPO_SLUG}/svg-sprite_travis_${TRAVIS_BUILD_NUMBER}.tar.bz2"

matrix:
  fast_finish: true
